#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet
# Configure Nginx to run and listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
echo "" > /run/nginx.pid
